<?php

  /**
   * Implements hook_library().
   */
  function zurb_responsive_tables_page_build($page) {
    libraries_load('responsive-tables');
  }

  /**
   * Implement hook_libraries_info().
   */
  function zurb_responsive_tables_libraries_info() {
    $libraries['responsive-tables'] = array(
      'name' => 'Zurb Responsive Tables',
      'vendor url' => 'http://zurb.com/playground/responsive-tables',
      'download url' => 'https://github.com/zurb/responsive-tables',
      'version' => '1.0',
      'files' => array(
        'js' => array(
          'responsive-tables.js',
        ),
        'css' => array(
          'responsive-tables.css',
        ),
      ),
    );

    return $libraries;
  }
